# Generated by Django 5.2.12 on 2026-03-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='buyer',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
