# Generated by Django 5.2.12 on 2026-03-24 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.prodsales'),
        ),
    ]
