# Generated by Django 5.2.11 on 2026-03-24 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='FK',
            new_name='products',
        ),
    ]
