# Generated by Django 5.2.12 on 2026-03-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_fk_cart_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
    ]
